package io.transwarp.tdc.gn.common;

public interface NotificationConsumerRecord<T> {

    /**
     * Used when dedupe the record, by default, could be
     * combination of identity fields generated by the underlying
     * storage or keys defined by business logic
     * @return
     */
    String guid();

    String topic();

    String group();

    int partition();

    long offset();

    long createTime();

    T payload();
}
