server:
  port: 23333

gn:
  service:
    impl: kafka

spring:
  profiles:
    include: persistence

kafka:
  producer:
    bootstrapServers: 127.0.0.1:9092
    acks: all
    retries: 0
    batchSize: 16384
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/notice?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123456
  schema: classpath:schema/message_remain.sql
