mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.ts.tdc.gn.model
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers:
    - io.ts.mangix.web.mybatis.BaseMapper

pagehelper:
  support-methods-arguments: true
