package io.ts.tdc.gn.common;

public interface NotificationConsumerRecord<T> {

    /**
     * Used when dedupe the record, by default, could be
     * combination of identity fields generated by the underlying
     * storage or keys defined by business logic
     * @return
     */
    String guid();

    /**
     * the topic that this record belongs
     * @return
     */
    String topic();

    /**
     * the group which is currently consuming
     * @return
     */
    String group();

    /**
     * partition that this record belongs, only meaningful for Kafka
     * @return
     */
    int partition();

    /**
     * the offset of this record
     * @return
     */
    long offset();

    /**
     * the create time of this record
     * @return
     */
    long createTime();

    /**
     * the actual payload
     * @return
     */
    T payload();
}
